#!/usr/bin/env sh
set -e

APP_PORT=10000
sed -ri -e "s/^Listen [0-9]+\$/Listen ${APP_PORT}/" /etc/apache2/ports.conf
sed -ri -e "s/<VirtualHost \*:[0-9]+>/<VirtualHost *:${APP_PORT}>/" /etc/apache2/sites-available/000-default.conf

mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache

# Fix permissions
touch storage/logs/laravel.log
chown -R www-data:www-data storage bootstrap/cache
chmod -R 777 storage bootstrap/cache

cat > .env << EOF
APP_NAME="${APP_NAME}"
APP_ENV="${APP_ENV}"
APP_KEY="${APP_KEY}"
APP_DEBUG="${APP_DEBUG}"
APP_URL="${APP_URL}"
FRONTEND_URL="${FRONTEND_URL}"
CORS_ALLOWED_ORIGINS="${CORS_ALLOWED_ORIGINS}"
SANCTUM_STATEFUL_DOMAINS="${SANCTUM_STATEFUL_DOMAINS}"
LOG_CHANNEL="${LOG_CHANNEL:-stderr}"
LOG_LEVEL="${LOG_LEVEL:-debug}"
DB_CONNECTION="${DB_CONNECTION}"
DB_HOST="${DB_HOST}"
DB_PORT="${DB_PORT}"
DB_DATABASE="${DB_DATABASE}"
DB_USERNAME="${DB_USERNAME}"
DB_PASSWORD="${DB_PASSWORD}"
DB_SSLMODE="${DB_SSLMODE}"
SESSION_DRIVER="${SESSION_DRIVER:-cookie}"
SESSION_LIFETIME="${SESSION_LIFETIME}"
SESSION_SECURE_COOKIE="${SESSION_SECURE_COOKIE}"
SESSION_SAME_SITE="${SESSION_SAME_SITE}"
SESSION_DOMAIN="${SESSION_DOMAIN}"
CACHE_STORE="${CACHE_STORE:-database}"
QUEUE_CONNECTION="${QUEUE_CONNECTION:-sync}"
FILESYSTEM_DISK="${FILESYSTEM_DISK:-local}"
BROADCAST_DRIVER="${BROADCAST_DRIVER:-${BROADCAST_CONNECTION:-log}}"
BROADCAST_CONNECTION="${BROADCAST_CONNECTION:-${BROADCAST_DRIVER:-log}}"
PUSHER_APP_ID="${PUSHER_APP_ID}"
PUSHER_APP_KEY="${PUSHER_APP_KEY}"
PUSHER_APP_SECRET="${PUSHER_APP_SECRET}"
PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
PUSHER_PORT="${PUSHER_PORT}"
PUSHER_SCHEME="${PUSHER_SCHEME}"
MAIL_MAILER="${MAIL_MAILER:-smtp}"
MAIL_FROM_ADDRESS="${MAIL_FROM_ADDRESS}"
MAIL_FROM_NAME="${MAIL_FROM_NAME}"
BREVO_API_KEY="${BREVO_API_KEY}"
BREVO_HOST="${BREVO_HOST}"
BREVO_PORT="${BREVO_PORT}"
BREVO_USERNAME="${BREVO_USERNAME}"
BREVO_PASSWORD="${BREVO_PASSWORD}"
BREVO_ENCRYPTION="${BREVO_ENCRYPTION}"
BREVO_FROM_ADDRESS="${BREVO_FROM_ADDRESS}"
BREVO_FROM_NAME="${BREVO_FROM_NAME}"
AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
AWS_REGION="${AWS_REGION}"
AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"
AWS_REKOGNITION_COLLECTION="${AWS_REKOGNITION_COLLECTION}"
AWS_REKOGNITION_THRESHOLD="${AWS_REKOGNITION_THRESHOLD}"
SCOUT_DRIVER="${SCOUT_DRIVER:-database}"
SCOUT_QUEUE="${SCOUT_QUEUE}"
MEILISEARCH_HOST="${MEILISEARCH_HOST}"
MEILISEARCH_KEY="${MEILISEARCH_KEY}"
CLOUDINARY_URL="${CLOUDINARY_URL}"
CLOUDINARY_CLOUD_NAME="${CLOUDINARY_CLOUD_NAME}"
CLOUDINARY_API_KEY="${CLOUDINARY_API_KEY}"
CLOUDINARY_API_SECRET="${CLOUDINARY_API_SECRET}"
PAYMONGO_SECRET_KEY="${PAYMONGO_SECRET_KEY}"
PAYMONGO_PUBLIC_KEY="${PAYMONGO_PUBLIC_KEY}"
PAYMONGO_WEBHOOK_SECRET="${PAYMONGO_WEBHOOK_SECRET}"
GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}"
GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}"
GOOGLE_REDIRECT_URI="${GOOGLE_REDIRECT_URI}"
FIREBASE_CREDENTIALS="${FIREBASE_CREDENTIALS}"
GROQ_API_KEY="${GROQ_API_KEY}"
GROQ_WHISPER_MODEL="${GROQ_WHISPER_MODEL}"
WHISPER_MODEL="${WHISPER_MODEL}"
GROQ_TEXT_MODEL="${GROQ_TEXT_MODEL}"
FACE_RECOGNITION_DRIVER="${FACE_RECOGNITION_DRIVER}"
FACE_RECOGNITION_THRESHOLD="${FACE_RECOGNITION_THRESHOLD}"
FACE_SERVICE_URL="${FACE_SERVICE_URL}"
WHISPER_SERVICE_URL="${WHISPER_SERVICE_URL}"
EOF

php artisan config:cache
php artisan route:cache
php artisan view:cache
chown -R www-data:www-data storage bootstrap/cache

QUEUE_DRIVER_IN_USE="${QUEUE_CONNECTION:-sync}"
echo "[render-start] mailer=${MAIL_MAILER:-smtp} queue=${QUEUE_DRIVER_IN_USE} brevo_api_key=$([ -n "${BREVO_API_KEY}" ] && echo set || echo missing) port=${APP_PORT}"

# Render runs only this container, so non-sync queues need an in-container worker or jobs sit in the jobs table forever.
if [ "${QUEUE_DRIVER_IN_USE}" != "sync" ]; then
    (
        while true; do
            su -s /bin/sh www-data -c "php artisan queue:work --sleep=3 --tries=3 --timeout=120 --max-time=3600" || true
            sleep 5
        done
    ) &
    echo "[render-start] queue worker started for connection=${QUEUE_DRIVER_IN_USE}"
fi

exec apache2-foreground
